- name: 🛠️ Init buildozer
  run: buildozer android debug || true

- name: 📜 Accept licenses
  run: |
    mkdir -p /home/runner/.android
    touch /home/runner/.android/repositories.cfg
    yes | /github/home/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses || true

- name: ⚙️ Set SDK config
  run: |
    mkdir -p ~/.android
    echo "count=0" > ~/.android/repositories.cfg

- name: 🧩 Install Android SDK
  run: |
    yes | /github/home/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager \
      "platform-tools" \
      "platforms;android-33" \
      "build-tools;33.0.2" || true

- name: 🚀 Build APK
  run: buildozer android debug
